export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';

export const CATEGORY_REMOVE = 'CATEGORY_REMOVE';
export const CATEGORY_ADD = 'CATEGORY_ADD';